import type { Metadata } from "next";
import "./globals.css";
import { Anouncement } from "@/components/Announcement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white antialiased`}
      >
        <Anouncement />
        {children}
      </body>
    </html>
  );
}
